export const CATEGORIES_GET_REQUEST = "CATEGORIES_GET_REQUEST";
export const CATEGORIES_GET_SUCCESS = "CATEGORIES_GET_SUCCESS";
export const CATEGORIES_GET_ERROR = "CATEGORIES_GET_ERROR";

export const REPORT_SEARCH_GET_REQUEST = "REPORT_SEARCH_GET_REQUEST";
export const REPORT_SEARCH_GET_SUCCESS = "REPORT_SEARCH_GET_SUCCESS";
export const REPORT_SEARCH_GET_ERROR = "REPORT_SEARCH_GET_ERROR";
